name: Build Android
on:
  workflow_call:
    inputs:
      build_type:
        required: false
        type: string
        default: Debug
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  CMAKE_BUILD_TYPE: ${{inputs.build_type}}

jobs:
  build:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current repo
        uses: actions/checkout@v3.4.0
      
      - name: Checkout axmol
        uses: actions/checkout@v3.4.0
        with:
          repository: axmolengine/axmol
          ref: 'release'
          path: 'axmol'
          submodules: 'recursive'
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
    
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2
      
      - name: Setup Python
        uses: actions/setup-python@v4.5.0

      - name: Create Build Environment
        run: |
          sdkmanager 'ndk;25.2.9519653'
          echo "" | tee ~/.bashrc
          axmol/tools/unix-ci/before-install.sh
          sed -i 's/if(DBus1_FOUND OR DBUS_FOUND)/if(FALSE)/' axmol/thirdparty/openal/CMakeLists.txt
      
      - name: Build axmol
        run: python3 axmol/setup.py
      
      - name: Build OpenGD
        env:
          AX_ROOT: "/home/runner/work/OpenGD/OpenGD/axmol/"
          AX_CONSOLE_ROOT: "/home/runner/work/OpenGD/OpenGD/axmol/tools/console/bin"
        run: |
          source ~/.bashrc
          cd proj.android
          ./gradlew assembleDebug -PPROP_BUILD_TYPE=cmake -PPROP_APP_ABI=arm64-v8a --parallel --info
          cd ..
      - uses: actions/upload-artifact@v3
        with:
          name: Debug APK
          path: ./proj.android/app/build/outputs/

