name: Build Linux
on:
  workflow_call:
    inputs:
      build_type:
        required: false
        type: string
        default: Debug
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  CMAKE_BUILD_TYPE: ${{inputs.build_type}}


jobs:
  build:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current repo
        uses: actions/checkout@v3.4.0
      
      - name: Checkout axmol
        uses: actions/checkout@v3.4.0
        with:
          repository: axmolengine/axmol
          ref: 'release'
          path: 'axmol'
          submodules: 'recursive'
      
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
      

      - name: Create Build Environment
        run: |
          echo "" | tee ~/.bashrc
          axmol/tools/unix-ci/before-install.sh
          sudo apt install -y libxrandr-dev \
              libxinerama-dev libxcursor-dev \
              libxcb-xinput-dev xorg-dev \
              libgtk-3-dev clang-13
          # sed -i 's/if(DBus1_FOUND OR DBUS_FOUND)/if(FALSE)/' axmol/thirdparty/openal/CMakeLists.txt
      
      - name: Build axmol
        run: python3 axmol/setup.py
      
      - name: Cache Build (to speed up subsequent builds)
        id: build-cache
        uses: actions/cache@v3
        env:
          cache-name: linux-build-cache-${{github.sha}}
        with:
          path: linux-build
          key: linux-build-cache-${{github.sha}}
          restore-keys: |
            linux-build-cache-${{github.sha}}
            linux-build-cache-

      - name: Build OpenGD
        env:
          AX_ROOT: "/home/runner/work/OpenGD/OpenGD/axmol/"
          AX_CONSOLE_ROOT: "/home/runner/work/OpenGD/OpenGD/axmol/tools/console/bin"
        run: |
          source ~/.bashrc
          cmake -B build
          cmake --build build
          cp -r build/bin bin
      - uses: actions/upload-artifact@v3
        with:
          name: Debug_Linux_Binary
          path: ./bin/${{env.CMAKE_BUILD_TYPE}}/linux/

